---
title: "daily_weather"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{daily_weather}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(azmetr)
library(lubridate)
library(ggplot2)
```

Get the most recent day of data for all stations simply by calling `az_daily()` without any arguments.

```{r}
az_daily()
```

Get the past week of data using `start_date`

```{r}
last_week <- lubridate::today() - lubridate::weeks(1)
all_wk <- az_daily(start_date = last_week)
ggplot(all_wk, aes(x = datetime, y = temp_air_meanC, color = meta_station_name)) +
  geom_line() +
  labs(title = "Previous week's temperatures",
       x = "Date",
       y = "Mean air temperature (ºC)",
       color = "Station")
```

Get just a subset of stations

```{r}
sub_wk <- az_daily(station_id = c(1, 2, 8), start_date = last_week)
ggplot(sub_wk, aes(x = datetime, y = wind_spd_mean_mph, fill = meta_station_name)) +
  geom_col(position = "dodge") +
  labs(title = "Previous week's max wind speed",
       x = "Date",
       y = "Max wind speed (mph)",
       fill = "Station")
```

