# fmt: skip file

add_labels_hourly <- function(hourly) {
  attr(hourly$meta_bat_volt, "label") <- "Battery voltage (V)"
  attr(hourly$meta_needs_review, "label") <- "Data quality flag"
  attr(hourly$meta_station_id, "label") <- "Station ID"
  attr(hourly$meta_station_name, "label") <- "Station"
  attr(hourly$meta_version, "label") <- "Data version"
  attr(hourly$date_datetime, "label") <- "Measurement timestamp"
  attr(hourly$date_doy, "label") <- "Day of year"
  attr(hourly$date_hour, "label") <- "Hour"
  attr(hourly$date_year, "label") <- "Year"
  attr(hourly$dwpt, "label") <- "Avg. dewpoint (\u00b0C)"
  attr(hourly$dwptF, "label") <- "Avg. dewpoint (\u00b0F)"
  attr(hourly$eto_azmet, "label") <- "Reference evapotranspiration (mm)"
  attr(hourly$eto_azmet_in, "label") <- "Reference evapotranspiration (in)"
  attr(hourly$heatstress_cottonC, "label") <- "Estimated avg. canopy temperature (\u00b0C)"
  attr(hourly$heatstress_cottonF, "label") <- "Estimated avg. canopy temperature (\u00b0F)"
  attr(hourly$precip_total, "label") <- "Precipitation (mm)"
  attr(hourly$precip_total_in, "label") <- "Precipitation (in)"
  attr(hourly$relative_humidity, "label") <- "Avg. RH (%)"
  attr(hourly$sol_rad_total, "label") <- "Solar radiation (MJ/m^2)"
  attr(hourly$sol_rad_total_ly, "label") <- "Solar radiation (ly)"
  attr(hourly$temp_airC, "label") <- "Avg. air temperature (\u00b0C)"
  attr(hourly$temp_airF, "label") <- "Avg. air temperature (\u00b0F)"
  attr(hourly$temp_soil_10cmC, "label") <- "Soil temperature at 10cm (\u00b0C)"
  attr(hourly$temp_soil_10cmF, "label") <- "Soil temperature at 10cm (\u00b0F)"
  attr(hourly$temp_soil_50cmC, "label") <- "Soil temperature at 50cm (\u00b0C)"
  attr(hourly$temp_soil_50cmF, "label") <- "Soil temperature at 50cm (\u00b0F)"
  attr(hourly$vp_actual, "label") <- "Avg. actual vapor pressure (kPa)"
  attr(hourly$vp_deficit, "label") <- "Avg. vapor pressure deficit (kPa)"
  attr(hourly$wind_2min_spd_max_mph, "label") <- "Max. two-minute sustained wind speed (mi/h)"
  attr(hourly$wind_2min_spd_max_mps, "label") <- "Max. two-minute sustained wind speed (m/s)"
  attr(hourly$wind_2min_spd_mean_mph, "label") <- "Avg. two-minute sustained wind speed (mi/h)"
  attr(hourly$wind_2min_spd_mean_mps, "label") <- "Avg. two-minute sustained wind speed (m/s)"
  attr(hourly$wind_2min_timestamp, "label") <- "Timestamp of max. two-minute sustained wind speed"
  attr(hourly$wind_2min_vector_dir, "label") <- "Wind vector direction of max. two-minute sustained wind speed (\u00b0)"
  attr(hourly$wind_spd_max_mph, "label") <- "Max. wind speed (mi/h)"
  attr(hourly$wind_spd_max_mps, "label") <- "Max. wind speed (m/s)"
  attr(hourly$wind_spd_mph, "label") <- "Avg. wind speed (mi/h)"
  attr(hourly$wind_spd_mps, "label") <- "Avg. wind speed (m/s)"
  attr(hourly$wind_vector_dir, "label") <- "Avg. wind vector direction (\u00b0)"
  attr(hourly$wind_vector_dir_stand_dev, "label") <- "Wind vector direction SD (\u00b0)"
  attr(hourly$wind_vector_magnitude, "label") <- "Avg. wind vector magnitude (m/s)"
  attr(hourly$wind_vector_magnitude_mph, "label") <- "Avg. wind vector magnitude (mi/h)"
  
  hourly
}
