add_labels_daily <- function(daily) {
  attr(daily$meta_bat_volt_max, "label") <- "Max. battery voltage"
  attr(daily$meta_bat_volt_mean, "label") <- "Avg. battery voltage"
  attr(daily$meta_bat_volt_min, "label") <- "Min. battery voltage"
  attr(daily$meta_needs_review, "label") <- "Data quality flag"
  attr(daily$meta_station_id, "label") <- "Station ID"
  attr(daily$meta_station_name, "label") <- "Station"
  # attr(daily$meta_version , "label") <-
  attr(daily$chill_hours_0C, "label") <- "Chill hours 0\u00b0C (h)"
  attr(daily$chill_hours_20C, "label") <- "Chill hours 20\u00b0C (h)"
  attr(daily$chill_hours_32F, "label") <- "Chill hours 32\u00b0F (h)"
  attr(daily$chill_hours_45F, "label") <- "Chill hours 45\u00b0F (h)"
  attr(daily$chill_hours_68F, "label") <- "Chill hours 68\u00b0F (h)"
  attr(daily$chill_hours_7C, "label") <- "Chill hours 7\u00b0C (h)"
  attr(daily$date_doy, "label") <- "Day of year"
  attr(daily$date_year, "label") <- "Year"
  attr(daily$datetime, "label") <- "Date"
  attr(daily$dwpt_mean, "label") <- "Mean dewpoint (\u00b0C)"
  attr(daily$dwpt_meanF, "label") <- "Mean dewpoint (\u00b0F)"
  attr(daily$eto_azmet, "label") <- "Potential evapotranspiration (mm)"
  attr(daily$eto_azmet_in, "label") <- "Potential evapotranspiration (in)"
  attr(daily$eto_pen_mon, "label") <- "Potential evapotranspiration (mm)"
  attr(daily$eto_pen_mon_in, "label") <- "Potential evapotranspiration (in)"
  attr(daily$heat_units_10C, "label") <- "Heat units 30-10\u00b0C	(degree-days)"
  attr(daily$heat_units_13C, "label") <- "Heat units 30-13\u00b0C	(degree-days)"
  attr(daily$heat_units_3413C, "label") <- "Heat units 34-13\u00b0C	(degree-days)"
  attr(daily$heat_units_45F, "label") <- "Heat units 86-45\u00b0F	(degree-days)"
  attr(daily$heat_units_50F, "label") <- "Heat units 86-50\u00b0F	(degree-days)"
  attr(daily$heat_units_55F, "label") <- "Heat units 86-55\u00b0F	(degree-days)"
  attr(daily$heat_units_7C, "label") <- "Heat units 30-7\u00b0C	(degree-days)"
  attr(daily$heat_units_9455F, "label") <- "Heat units 94-55\u00b0F (degree-days)"
  attr(daily$heatstress_cotton_meanC, "label") <- "Cotton heatstress (\u00b0C)"
  attr(daily$heatstress_cotton_meanF, "label") <- "Cotton heatstress (\u00b0F)"
  attr(daily$precip_total_in, "label") <- "Precipitation (in)"
  attr(daily$precip_total_mm, "label") <- "Precipitation (mm)"
  attr(daily$relative_humidity_max, "label") <- "Max. RH (%)"
  attr(daily$relative_humidity_mean, "label") <- "Avg. RH (%)"
  attr(daily$relative_humidity_min, "label") <- "Min. RH (%)"
  attr(daily$sol_rad_total, "label") <- "Solar radiation (MJ/m^2)"
  attr(daily$sol_rad_total_ly, "label") <- "Solar radiation (ly)"
  attr(daily$temp_air_maxC, "label") <- "Max. air temperature (\u00b0C)"
  attr(daily$temp_air_maxF, "label") <- "Max. air temperature (\u00b0F)"
  attr(daily$temp_air_meanC, "label") <- "Avg. air temperature (\u00b0C)"
  attr(daily$temp_air_meanF, "label") <- "Avg. air temperature (\u00b0F)"
  attr(daily$temp_air_minC, "label") <- "Min. air temperature (\u00b0C)"
  attr(daily$temp_air_minF, "label") <- "Min. air temperature (\u00b0F)"
  attr(daily$temp_soil_10cm_maxC, "label") <- "Max. soil temperature at 10cm (\u00b0C)"
  attr(daily$temp_soil_10cm_maxF, "label") <- "Max. soil temperature at 10cm (\u00b0F)"
  attr(daily$temp_soil_10cm_meanC, "label") <- "Avg. soil temperature at 10cm (\u00b0C)"
  attr(daily$temp_soil_10cm_meanF, "label") <- "Avg. soil temperature at 10cm (\u00b0F)"
  attr(daily$temp_soil_10cm_minC, "label") <- "Min. soil temperature at 10cm (\u00b0C)"
  attr(daily$temp_soil_10cm_minF, "label") <- "Min. soil temperature at 10cm (\u00b0F)"
  attr(daily$temp_soil_50cm_maxC, "label") <- "Max. soil temperature at 50cm (\u00b0C)"
  attr(daily$temp_soil_50cm_maxF, "label") <- "Max. soil temperature at 50cm (\u00b0F)"
  attr(daily$temp_soil_50cm_meanC, "label") <- "Avg. soil temperature at 50cm (\u00b0C)"
  attr(daily$temp_soil_50cm_meanF, "label") <- "Avg. soil temperature at 50cm (\u00b0F)"
  attr(daily$temp_soil_50cm_minC, "label") <- "Min. soil temperature at 50cm (\u00b0C)"
  attr(daily$temp_soil_50cm_minF, "label") <- "Min. soil temperature at 50cm (\u00b0F)"
  attr(daily$vp_actual_max, "label") <- "Max. actual vapor pressure (kPa)"
  attr(daily$vp_actual_mean, "label") <- "Avg. actual vapor pressure (kPa)"
  attr(daily$vp_actual_min, "label") <- "Min. actual vapor pressure (kPa)"
  attr(daily$vp_deficit_mean, "label") <- "Vapor pressure deficit (kPa)"
  attr(daily$wind_2min_spd_max_mph, "label") <- "Max. two-minute sustained wind speed (miles/hr)"
  attr(daily$wind_2min_spd_max_mps, "label") <- "Max. two-minute sustained wind speed (m/s)"
  attr(daily$wind_2min_spd_mean_mph, "label") <- "Avg. two-minute sustained wind speed (miles/hr)"
  attr(daily$wind_2min_spd_mean_mps, "label") <- "Avg. two-minute sustained wind speed (m/s)"
  attr(daily$wind_2min_timestamp, "label") <- "Datetime"
  attr(daily$wind_2min_vector_dir, "label") <- "Wind vector direction (\u00b0)"
  attr(daily$wind_spd_max_mph, "label") <- "Max. wind speed (miles/hr)"
  attr(daily$wind_spd_max_mps, "label") <- "Max. wind speed (m/s)"
  attr(daily$wind_spd_mean_mph, "label") <- "Avg. wind speed (miles/hr)"
  attr(daily$wind_spd_mean_mps, "label") <- "Avg. wind speed (m/s)"
  attr(daily$wind_vector_dir, "label") <- "Wind vector direction (\u00b0)"
  attr(daily$wind_vector_dir_stand_dev, "label") <- "Wind vector direction SD (\u00b0)"
  attr(daily$wind_vector_magnitude, "label") <- "Wind vector magnitude (m/s)"
  attr(daily$wind_vector_magnitude_mph, "label") <- "Wind vector magnitude (miles/hr)"

  daily
}